### ISSUE TITLE
add iris

### ISSUE THREAD

**Issue by phamdt** [diyan/go-web-framework-comparsion#9]
https://github.com/kataras/iris

**Comment by diyan** [comment]
@phamdt With all my respect, it's not going to be added.

See more here:
http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html
https://github.com/avelino/awesome-go/pull/1135
https://github.com/avelino/awesome-go/pull/1137

**Comment by phamdt** [comment]
Ya i actually found that article right after i posted this so not adding makes sense to me.
